### PR TITLE
Migrate to jenkins-pipeline-library containerbuild

### PR DESCRIPTION
**Pull request by heurtematte**
Migrate docker builds to jenkins-pipeline-library

https://gitlab.eclipse.org/eclipsefdn/it/releng/jenkins-pipeline-service/jenkins-pipeline-library

### CODE REVIEW

**Comment by heurtematte** [comment]
Parallel build added: 
image

**Comment by fredg02** [comment]
@heurtematte sorry for the delay. Please solve the conflict and/or rebase, so this change can be merged.

**Comment by fredg02** [comment]
@heurtematte ping

**Comment by heurtematte** [comment]
PR ready to merge :rocket:

**Review by fredg02 — APPROVED** [review]

**Pull request merged**
