### PR TITLE
Update hugo and nodejs versions to fix docker build

### PR DESCRIPTION
**Pull request by fredg02**
cc @chrisguindon can you/your team update the relevant places where the stack-build-agent docker image is referenced?

### CODE REVIEW

**Comment by chrisguindon** [comment]
@fredg02 I have no idea what this is for.

**Comment by chrisguindon** [comment]
I assumed this was something that your team created to support hugo websites for Eclipse Projects.

**Comment by autumnfound** [comment]
> I assumed this was something that your team created to support hugo websites for Eclipse Projects. Not sure what I can do about this..

No this was our team. This is used to compile all of our Java projects, as we needed at least node js to compile some of our validation assets. Hugo was added a while back as we have a project or two with the bin, so it was easier to just add it here to stay consistent.

**Comment by chrisguindon** [comment]
> I assumed this was something that your team created to support hugo websites for Eclipse Projects. Not sure what I can do about this..

I took a closer look at the history for these files and I see this is something that @autumnfound created.

@autumnfound Can you take a look at @fredg02 request please when you get a chance.

**Comment by fredg02** [comment]
I will merge this, I only open the PR to raise awareness. :)

**Comment by chrisguindon** [comment]
> No this was our team. This is used to compile all of our Java projects, as we needed at least node js to compile some of our validation assets. Hugo was added a while back as we have a project or two with the bin, so it was easier to just add it here to stay consistent.

Yep, I assumed too fast without looking deeper. Can you take on the task of updating the node to the latest security update? I suspect we will be mostly fine as-long as we don't need to upgrade to a major version.

**Pull request merged**
