### PR TITLE
Create initial  Drupal 10 tag

### PR DESCRIPTION
**Pull request by chrisguindon**

### CODE REVIEW

**Comment by chrisguindon** [comment]
I am thinking that we should only update https://github.com/EclipseFdn/dockerfiles/blob/master/drupal-node/Dockerfile and tag this new tag as the latest next week once we are using this on production for all our sites.

//cc @theodoreb

**Comment by theodoreb** [comment]
That works for me

**Comment by chrisguindon** [comment]
The tag that will be created with this will be "d10.2.2-n18.19.0".  We will have to set that in our Dockerfile for each Drupal sites as they are currently set to "lastest"

**Comment by theodoreb** [comment]
I'd the the opposite, have latest point to D10 and update the sites that still uses D9 with a tag since they shouldn't be around for long

**Review by ericpoirier — APPROVED** [review]

**Pull request merged**
