### PR TITLE
Upgrade buildkit 0.12.2 and crane 0.16.1

### PR DESCRIPTION
**Pull request by heurtematte**

### CODE REVIEW

**Comment by fredg02** [comment]
Did you test this with a build that uses this image?

**Comment by mbarbero** [comment]
> Did you test this with a build that uses this image?

^^ what he says, but otherwise, +1 to upgrade

**Comment by heurtematte** [comment]
Test with gitlab-ci, see pipeline https://gitlab.eclipse.org/eclipsefdn/it/releng/gitlab-runner-service/gitlab-ci-templates/-/jobs/280006
and a docker image pushed in my own dockerhub repository: heurtemattes/containertools.

@mbarbero Do I have in parallel to restart all buildkit instance in okd infrastructure? 
where is the source code for foundation-internal-infra-buildkitd

**Comment by mbarbero** [comment]
> Test with gitlab-ci, see pipeline https://gitlab.eclipse.org/eclipsefdn/it/releng/gitlab-runner-service/gitlab-ci-templates/-/jobs/280006 and a docker image pushed in my own dockerhub repository: heurtemattes/containertools.
> 
> @mbarbero Do I have in parallel to restart all buildkit instance in okd infrastructure? where is the source code for foundation-internal-infra-buildkitd

https://github.com/eclipse-cbi/buildkitd-okd

**Review by fredg02 — APPROVED** [review]

**Pull request merged**
